/* Generated by VDGG */

package org.openmim.infrastructure.taskmanager;

/**
 *
 *
 * @author VDGG
 * @version 1.0
 * @since 1.0
 */
public interface Task {
    final static int CREATED = 0;
    final static int ONSTART = 1;
    final static int INPROCESS = 2;
    final static int TERMINATED = 3;

    void execute() throws Exception;

    String getId();

    int getState();

    void terminate();

    long getStartTime();

    boolean terminatable();
}

